# Generated by Django 5.1.2 on 2025-11-10 20:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_users_petsadopted_remove_users_petshelped'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='accountDate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='users',
            name='petsAdopted',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='users',
            name='petsHelped',
            field=models.IntegerField(default=0),
        ),
    ]
