# Generated by Django 5.1.2 on 2025-12-06 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_reports_administrator_alter_reports_moderator'),
    ]

    operations = [
        migrations.AddField(
            model_name='reports',
            name='reportedPublication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='publication_reported', to='api.publications'),
        ),
    ]
