# Generated by Django 5.1.2 on 2025-12-12 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_users_firstname_alter_users_lastname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='description',
            field=models.CharField(max_length=1000),
        ),
    ]
