# Generated by Django 5.1.2 on 2025-12-11 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_reports_reportedpublication'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='isBanned',
            field=models.BooleanField(default=False),
        ),
    ]
