# Generated by Django 5.1.2 on 2025-12-12 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_tickets_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audittickets',
            old_name='moderatorAsnwer',
            new_name='moderatorAnswer',
        ),
    ]
