# Generated by Django 5.1.2 on 2025-12-12 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_moderatorasnwer_audittickets_moderatoranswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audittickets',
            name='moderatorAnswer',
            field=models.CharField(max_length=1000),
        ),
    ]
