# Generated by Django 5.1.2 on 2025-11-12 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_ticketsstatus_alter_users_password_tickets'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='isBanned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='users',
            name='isMember',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Tickets',
        ),
    ]
