# Generated by Django 5.1.2 on 2025-12-11 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_users_isbanned'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='isHidden',
            field=models.BooleanField(default=False),
        ),
    ]
