# Generated by Django 5.1.2 on 2025-11-12 18:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_users_isbanned_users_ismember_delete_tickets'),
    ]

    operations = [
        migrations.CreateModel(
            name='Breeds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='unknown', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ReportGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameSpecie', models.CharField(default='unknown', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='unknown', max_length=50)),
                ('age', models.IntegerField(default=0)),
                ('vaccinated', models.CharField(default='unknown', max_length=50)),
                ('isActive', models.BooleanField(default=True)),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.breeds')),
                ('keeper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.users')),
            ],
        ),
        migrations.CreateModel(
            name='MediaPets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='imagenes/')),
                ('video', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.pets')),
            ],
        ),
        migrations.CreateModel(
            name='Publications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('reward', models.IntegerField(blank=True, null=True)),
                ('datePublications', models.DateField(default=django.utils.timezone.now)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.pets')),
            ],
        ),
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem', models.CharField(max_length=100)),
                ('userDescription', models.CharField(max_length=500)),
                ('moderatorDescription', models.CharField(blank=True, max_length=500, null=True)),
                ('adminDescription', models.CharField(blank=True, max_length=500, null=True)),
                ('dateReport', models.DateField(default=django.utils.timezone.now)),
                ('administrator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_as_admin', to='api.users')),
                ('moderator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_as_moderator', to='api.users')),
                ('reportGrade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.reportgrade')),
                ('reportedUser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports_as_reported', to='api.users')),
                ('reporterUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_as_reporter', to='api.users')),
            ],
        ),
        migrations.AddField(
            model_name='breeds',
            name='specieBreed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.species'),
        ),
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300)),
                ('ticketDate', models.DateField(default=django.utils.timezone.now)),
                ('ticketstatus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ticketsstatus')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.users')),
            ],
        ),
        migrations.CreateModel(
            name='AuditTickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moderatorAsnwer', models.CharField(max_length=300)),
                ('answerDate', models.DateField(default=django.utils.timezone.now)),
                ('moderator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.users')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tickets')),
            ],
        ),
    ]
