# Generated by Django 5.1.2 on 2025-12-14 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_audittickets_moderatoranswer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='isHidden',
        ),
    ]
