# Generated by Django 5.1.2 on 2025-12-14 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_users_ishidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='publications',
            name='isHidden',
            field=models.BooleanField(default=False),
        ),
    ]
