# Generated by Django 5.1.2 on 2025-11-12 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_breeds_reportgrade_species_pets_mediapets_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pets',
            name='breed',
        ),
        migrations.RemoveField(
            model_name='mediapets',
            name='pet',
        ),
        migrations.RemoveField(
            model_name='pets',
            name='keeper',
        ),
        migrations.RemoveField(
            model_name='publications',
            name='pet',
        ),
        migrations.RemoveField(
            model_name='reports',
            name='reportGrade',
        ),
        migrations.RemoveField(
            model_name='reports',
            name='administrator',
        ),
        migrations.RemoveField(
            model_name='reports',
            name='moderator',
        ),
        migrations.RemoveField(
            model_name='reports',
            name='reportedUser',
        ),
        migrations.RemoveField(
            model_name='reports',
            name='reporterUser',
        ),
        migrations.DeleteModel(
            name='Breeds',
        ),
        migrations.DeleteModel(
            name='MediaPets',
        ),
        migrations.DeleteModel(
            name='Pets',
        ),
        migrations.DeleteModel(
            name='Publications',
        ),
        migrations.DeleteModel(
            name='ReportGrade',
        ),
        migrations.DeleteModel(
            name='Reports',
        ),
    ]
