# Generated by Django 5.1.2 on 2025-11-12 21:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_reportsgrade_breeds_pets_mediapets_publications_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.CharField(max_length=250)),
            ],
        ),
        migrations.AlterField(
            model_name='mediapets',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='mediapets/images/'),
        ),
        migrations.AlterField(
            model_name='mediapets',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='mediapets/videos/'),
        ),
        migrations.CreateModel(
            name='ChatsUsersModerators',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.chats')),
                ('member1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='User', to='api.users')),
                ('member2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Moderator', to='api.users')),
            ],
        ),
        migrations.CreateModel(
            name='ChatsUsersPets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.chats')),
                ('member1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member1', to='api.users')),
                ('member2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member2', to='api.users')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.pets')),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=1000)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('answerTo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='api.messages')),
                ('chat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.chats')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.users')),
            ],
        ),
        migrations.CreateModel(
            name='MediaMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='messagemedia/imagenes/')),
                ('video', models.FileField(blank=True, null=True, upload_to='messagemedia/videos/')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.messages')),
            ],
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(max_length=250)),
                ('reviewee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviewee', to='api.users')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviewer', to='api.users')),
            ],
        ),
    ]
