# Generated by Django 5.1.2 on 2025-11-13 03:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_mediamessages_imagen_alter_mediamessages_video_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HappyPets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.users')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.pets')),
            ],
        ),
    ]
